### ISSUE TITLE
Multiple unused utun interfaces after macOS upgrade

### ISSUE THREAD

**Issue by essandess** [Tunnelblick/Tunnelblick#340]
My Mac has several unused utun0, utun1, interfaces after upgrading to Sierra.

This causes a problem with pf firewalls because Tunnelblick randomly assigns its interface to one of these, and if it's not the default utun0 listed in `/etc/pf.conf`, the tunnel doesn't work.

Does anyone know how to destroy these unused interfaces so that Tunnelblick reliably grabs utun0 on launch?

Trying to destroy existing utun interfaces with ifconfig throws this error:

```
sudo ifconfig utun0 destroy
ifconfig: SIOCIFDESTROY: Invalid argument
```

See, e.g., this [pf.conf](../../../essandess/osx-openvpn-server/blob/master/pf.conf) that depends on knowing which utun interface Tunnelblick uses.

**Comment by jkbullard** [comment]
OpenVPN uses "/sbin/ifconfig utun0 delete" to delete utun0 ("delete", not "destroy"), so you might try that (with sudo).

Or maybe changing the "dev tun" option in the configuration to "dev utun0" would force OpenVPN to use utun0.

That could cause other problems, I suppose, because It is a little-used and little-tested option, so Tunnelblick may not deal with it properly. For example, you might need to tell Tunnelblick to never load its tun driver if Tunnelblick doesn't deal with the option properly. You can do that in the "Advanced" settings window. But that's just a guess, it may work fine.

(If you have "pf" expertise, have you considered helping Tunnelblick use "pf"? Please take a look at [this "help wanted" post](  https://groups.google.com/forum/#!topic/tunnelblick-discuss/rsr9knpBFsY).)

**Comment by essandess** [comment]
The ifconfig delete command reigns the following error, which appears in lots of Tunnelblick logs:

```
sudo ifconfig utun0 delete
ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
```

I was able to remove **most** of the superfluous utun devices by deleting their appearance in the routing table, then rebooting. I believe, but am not certain, that these unnecessary utun devices are related to repeated upgrades of Tunnelblick. The commands look like a bunch of this:

```
netstat -rn | grep utun
sudo route delete -inet6 -ifscope utun0 -net ff01::%utun0/32
sudo route delete -inet6 -ifscope utun2 default fe80::%utun2
sudo route delete -inet6 -ifscope utun3 -net fe80::%utun3
...
```

After these steps:

1. Delete utun appearance from routing table
2. Delete Tunnelblick
3. Reboot
4. Reinstall Tunnelblick

I **still** have a utun0 interface on boot.

For now, I've simply replaced `utun0` in `/etc/pf.conf` with `utun1` and hope that these interfaces don't swap names on boot.

**Comment by essandess** [comment]
Re: your [pf help wanted](https://groups.google.com/forum/#!topic/tunnelblick-discuss/rsr9knpBFsY) post

For now, I can point to a fully functional `pf.conf` firewall configuration for a Tunnelblick-based OpenVPN Server at the repo [osx-openvpn-server](../../../essandess/osx-openvpn-server/).

That has most (all?) of the tricks you need for a pf-based firewall with Tunnelblick.

**Comment by jkbullard** [comment]
Tunnelblick itself, and/or installing or uninstalling it, will not affect the utun devices.

It is OpenVPN that creates (and should destroy) the utun devices, and OpenVPN is only run when you connect to a VPN. My guess is that your OpenVPN configuration causes OpenVPN to not destroy the utun device when disconnecting, either because OpenVPN crashes before it deletes the utun device, or you are using "user nobody / group nobody" options in the OpenVPN configuration. If you do that, then OpenVPN is running as nobody when the configuration disconnects, and it is unable to destroy the utun device (which it can only do when it is running as root).

Depending on your setup, "user nobody / group nobody" may also leave bad entries in the routing table, because it can't remove the routes it created. Some configurations don't do any routing, so they don't have this problem.

Thanks for pointing to the `pf.conf` configuration; I'll take a look at it.

**Comment by essandess** [comment]
>

That's exactly what I'm doing in my OpenVPN server configuration file, [openvpn-server-tun.tblk/config.ovpn](../../../essandess/osx-openvpn-server/blob/master/openvpn-server-tun.tblk/config.ovpn)

```
user nobody
group nobody
```

I'll have to go off and think about the security implications of changing user and group permissions.

I'll bet the creation of the other `utun` devices I observed above were created when OpenVPN launched a server using this file.

**Comment by jkbullard** [comment]
Originally I was thinking you could use a custom "down" script
 * Take Tunnelblick's standard down script (/Applications/Tunnelblick.app/Contents/Resources/client.down.tunnelblick.sh) and modify it to do the additional cleanup that must be done as root. See the OpenVPN documentation for info on environment variables that the down script can use and the arguments it is invoked with. I think the arguments to the down script include the device name that the connection used (such as "utun0"), which would make it easy to delete that device. I don't know about obtaining the routing information, though -- or rather the "unrouting" information.
 * If you use the "openvpn-down-root" plugin (which will be used by Tunnelblick automatically if you agree to that), then the down script runs as root. At some point you may have told Tunnelblick to **not** use openvpn-down-root; otherwise it would ask you each time you try to connect a configuration with "user nobody / group nobody".


But I am not completely sure that it is OK for the down script to delete the device -- it would not be OK if OpenVPN does anything else with the device, I don't think it does but I don't really know.

As an alternative, you could use a custom "post-disconnect.sh" script that deletes the utun device. The catch there is that that script isn't given any info about the device (or anything else!), so it would have to hard-code the "utun0" or "utun1" or whatever.

Info on using scripts is available at [Using Scripts](https://tunnelblick.net/cUsingScripts.html).

Now that I'm thinking about it, maybe Tunnelblick should have an option in it

**Comment by essandess** [comment]
I'll need to debug this step-by-step.

Step 1: Do you know how to figure out what's creating the utun0 interface after a reboot *without* launching OpenVPN at boot?

**Comment by jkbullard** [comment]
It's OpenVPN itself that "creates" utun devices; Tunnelblick doesn't have anything to do with them.

Maybe you have a configuration set to connect "when system starts"? So when you restart, it would try to connect that configuration and create utun0.

Even if you don't, see if there is anything that mentions Tunnelblick or OpenVPN in /Library/LaunchDaemons. Maybe something got left there. If so, you can just delete it.

**Comment by essandess** [comment]
Re: pf firewall

Google groups is terrible—my response there was just lost twice, ado I'll post it here.

You'll want to use pf anchors for this. The pf directives will look like:

```
block all
# Allow OpenVPN
# Refresh with pfctl -a tunnelblick -T load -f /usr/local/etc/tunnelblick-ovpn.conf
anchor 'tunnelblick' label "Tunnelblick OpenVPN Rules"
load anchor 'tunnelblick' from '/usr/local/etc/tunnelblick-ovpn.conf'
```

The repo [osxfortress](../../../essandess/osxfortress) shows how to build a dynamic firewall using pf anchors and scripts.

This repo uses launchd plists to download open source threat data and update the firewall. It's obvious how to modify the example for your design. See these files:

* [pf.conf](../../../essandess/osxfortress/blob/master/pf.conf)
* [blockips.conf](../../../essandess/osxfortress/blob/master/blockips.conf)
* [net.emergingthreats.blockips.plist](../../../essandess/osxfortress/blob/master/net.emergingthreats.blockips.plist)

**Comment by jkbullard** [comment]
Thanks. It's totally off-topic, but:

I've already received this info two times (and responded once) in private emails that you sent, so there is definitely a problem somewhere. If you haven't gotten my response, here it is:

> Thanks. I'll look all this over carefully. I am aware of your work but
> didn't remember that it uses pf.
> 
> It's probably obvious, but what I'm looking to do is for an OpenVPN
> client, not a server, although I do understand that the pf mechanism
> is the same either way. I think the main difference is that on a
> server you want it to be active at boot and never deactivate, but on a
> client you want to be able to activate and deactivate it dynamically.
> 
> One basic question: Must I modify pf.conf, or can I do everything via
> pfctl? It looks to me like I have to define an anchor in pf.conf (with
> directives like you describe) before manipulating it with pfctl, but
> I'm really not clear about that. I really hate making modifications to
> system files directly because of possible race conditions and
> conflicts with other programs that my make modifications to them.

**Comment by essandess** [comment]
Still digging.

I have a plist `net.tunnelblick.tunnelblick.tunnelblickd.plist` that dumps logs to:

```
<key>StandardErrorPath</key>
<string>/var/log/Tunnelblick/tunnelblickd.log</string>
```

But the directory `/var/log/Tunnelblick` doesn't exist. Install bug?

**Comment by jkbullard** [comment]
That folder (/var/log/Tunnelblick) should be created (if it doesn't exist)
each time Tunnelblick runs its "installer".

That happens when you originally install Tunnelblick, when you install or
modify configurations, or make other changes that require Tunnelblick to
ask for a computer admin's username/password. The folder should be owned by
root:wheel with 0755 permissions.

I assume it's not a permissions problem – Tunnelblick doesn't try to repair
permissions on that folder because it should be the only thing creating it
and it is created by Tunnelblick's "installer" program with the proper
permissions.

**Comment by essandess** [comment]
I haven't been able to resolve this on the macOS or Tunnelblick sides, so I just added a bunch of extra rules to `pf.conf` for robustness in case it happens.

See https://github.com/essandess/osx-openvpn-server/commit/0be941bd01f91c74554f6221721f31a21d6dd678

**Comment by essandess** [comment]
Following up, unfortunately the fix to #493 doesn't address this issue. Here's what I see while running an OpenVPN server with Tunnelblick:

```
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::ca26:ff77:5a2a:8019%utun0 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.8.0.1 --> 10.8.0.2 netmask 0xffffffff 
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::2c03:3e37:c633:5ede%utun2 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::6e78:9f4:5364:ab26%utun3 prefixlen 64 scopeid 0x12 
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bbcb:aff:bb0b:e94%utun4 prefixlen 64 scopeid 0x13 
	nd6 options=201<PERFORMNUD,DAD>
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bee2:1994:fc74:d790%utun5 prefixlen 64 scopeid 0x14 
	nd6 options=201<PERFORMNUD,DAD>
utun6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::81b4:0775:c99d:a1ec%utun6 prefixlen 64 scopeid 0x15 
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by jkbullard** [comment]
@essandess - Please post the diagnostic info obtained by following the procedure, which is a modified version of the one found at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html):
 1. Make sure all Tunnelblick configurations are set to connect manually.
 1. Restart your computer.
 1. (Wait for the computer to completely start up.)
 1. Use `ifconfig -a`  to verify that no utun devices exist.
 1. Open Tunnelblick's "VPN Details" window.
 1. On the "Preferences" tab, please click the button to "Reset Disabled Warnings".
 1. On the "Configurations" tab, please select the configuration you want to connect in the list on the left.
 1. Make sure that "VPN log level" is set to "OpenVPN level 3 - normal output". This is the default setting; higher levels are for debugging OpenVPN itself, which is almost never needed and usually makes it harder to find the cause of a problem.
 1. Click the "Advanced" button; a new window will appear.
 1. Make sure "Keep connected" is not checked.
 1. Close the "Advanced Settings" window.
 1. Click on the "Log" tab.
 1. Click on the "Connect" button.
 1. Wait until the VPN is connected, then wait two minutes more.
 1. Click on the "Disconnect" button and wait until the disconnection is complete. If the disconnection is not complete within 60 seconds, continue anyway.
 1. Click on the "Copy Diagnostic Info to the Clipboard" button.
Wait for the copy to complete (there is a spinning progress indicator; when it disappears the copy is complete).
 1. Paste into an email or web form.
 1. Remove any sensitive information before sending the email or the form.

**Comment by bins90** [comment]
可以尝试使用 sudo ifconfig utun(数字序号) down
例如：sudo ifconfig utun1 down
输入个人用户密码确认删除

**Comment by jkbullard** [comment]
I think this was caused by the Tunnelblick down script fails. When that happens, a bug in OpenVPN causes OpenVPN to fail to destroy the utun interface.

Although AFAIK that bug still exists in OpenVPN, Tunnelblick's down script has been fixed so it should not fail, thus the OpenVPN bug will not be encountered.

**Comment by aikfiend** [comment]
@jkbullard it looks like my 10 month baby girl was able to reproduce this issue twice on Mac OS Mojave Version: 10.14.5 (18F132) just unplugging the power cable from Mac mini when Tunnelblick (version 3.7.9a (build 5321)) was launched and OpenVPN tunnel was created.
Could you please clarify in which version of Tunelblick it was fixed and which script exactly fixes that. I hope that I can find how I can remove `utun0` interface there.

**Comment by jkbullard** [comment]
@aikfiend - Tunnelblick 3.7.8beta03 includes the fixed scripts. They are used if you have set "DNS/WINS" to "Set nameserver".

However, they won't help you with removing extra utun devices. Neither Tunnelblick not its scripts create them or destroy them. OpenVPN creates them and should destroy them.

See the earlier comments by @essandess about his attempts to delete the extra utun interfaces.  A Google search for "remove utun" (without the quotation marks) shows some links with ideas. Note that one utun interface may be used by "Back to My Mac" or other macOS features [1], so you might not be able to delete all of them.

Or see Tunnelblick's [Support](https://tunnelblick.net/support.html) page for links to sources of help with OpenVPN; perhaps the OpenVPN users mailing list would get you some help deleting the utun devices.

**Tunnelblick 3.7.9a could have caused a different problem** with such a power loss, too. It could have left DNS set up for the VPN without restoring it to the pre-VPN values. (3.7.8beta03 won't do that.) To fix that:
 1. Open System Preferences
 1. Click on "Network"
 1. Click on the "Advanced" button
 1. Click on the "DNS" tab
 1. Click on each entry in the list on the left side ("DNS Servers") and click the minus button ("-") at the bottom of the list. If the entry is dim (grey instead of black, move on to the next step.
 1. Click on each entry in the list on the right side (Search domains") and click the minus button ("-") at the bottom of the list. √
 1. Click the "OK" button.
 1. Click the "Apply" button.
 1. Wait a few seconds for the changes to take effect.

[1] Answer by linuxdev2013 (confirmed by Ray de Groat) at https://superuser.com/questions/914685/what-is-creating-the-utun0-network-interface-on-osx-what-is-for-what-is-it-exa

**Comment by jkbullard** [comment]
@essandess and @aikfiend:

Since this "multiple utun" problem first appeared, I was assuming that since OpenVPN creates the utun device, it must be responsible for destroying it, too. I suspected that if the Tunnelblick "down" script failed, it caused OpenVPN to forget to destroy the utun device, leading to multiple utun devices. I never tested that assumption. Now I have, and it may have been wrong. Something else may be causing the multiple utun devices.

Although it's true that OpenVPN destroys the utun when it does a normal shutdown of the VPN connection, some testing with Tunnelblick 3.7.9a and 3.8.0beta03 in a 10.14.5 virtual machine seems to indicate that the utun devices that OpenVPN creates do not survive a computer restart.

After connecting to a VPN (which created utun1 because utun0 already existed), I crashed the VM by "stopping" it. As I understand it, that should result in OpenVPN not being able to clean up, because the VM halts without doing any cleanup of any kind. (This was a Parallels VM, and I used "Stop" – not "Shutdown", which does an orderly shutdown of the computer.)
 
On restarting the VM, utun1 was gone and only utun0 remained. (By "gone", I mean it didn't show up in the output of "netstat -nr".)

The same thing happens if I force quit Tunnelblick and then force quit OpenVPN while a VPN is connected: after that, the utun device seems to have disappeared. (That makes some sense because even a force quit "closes" file descriptors that the process has created, and, as described below, closing the file descriptor for utun is part of the procedure that OpenVPN uses to clean up when shutting down the VPN.)

So maybe something else is creating the utun devices? The first, utun0, seems to exist without OpenVPN ever being used. (It exists on a "virgin" 10.14.5 installation.)

**OpenVPN destroying utun devices**

I looked at OpenVPN's code to see how it destroys the utun devices. Although I wrote earlier that:
> OpenVPN uses "/sbin/ifconfig utun0 delete" to delete utun0 ("delete", not "destroy"), so you might try that (with sudo).

I now think that that code is actually used for some other purpose. It looks like OpenVPN destroys the utun device by doing two things (in tun.c):
 1. It does "route delete -inet6 ifconfig_ipv6_local" (I assume "ifconfig_ipv6_local" is some kind of ipv6 subnet specifier.)
 2. It does "close(tt->fd);" which closes the utun device by specifying it's file descriptor.

Thoughts?

**Comment by aikfiend** [comment]
![Screenshot 2019-07-21 at 18 08 38](https://user-images.githubusercontent.com/7749554/61999685-66260f80-b0cf-11e9-92e6-caffe5e45d7a.png)
Not bad, but as I see from [release notes](https://tunnelblick.net/cRlsNotes.html) - it has been fixed in 3.7.9a (build 5321). But my kid reproduced it in 3.7.9a (build 5321) 🤷‍♂

**Comment by jkbullard** [comment]
@aikfiend - Some, but not all, of the bugs that caused this problem were fixed in 3.7.9a. All known problems like this were fixed in 3.8.0.

**Comment by patrykk21** [comment]
I'm having the same issue and I have no idea what Tunnelblick is.

**Comment by jkbullard** [comment]
@patrykk21 - You have no idea what Tunnelblick is?

Tunnelblick is an application that lets you connect to certain kinds of VPN. It is free software, so many VPN service providers recommend it. Others rebrand it and supply it to their customers under other names (such as SurfBouncer, PersonalVPN, and myExpatNet).

So perhaps you have one of those rebranded versions of Tunnelblick, and perhaps it is an old version that still has this problem.

**Comment by essandess** [comment]
@jkbullard FWIW, I still see this issue with the latest version:
> `ifconfig -a`
```
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::225d:69a5:20b8:0b1e%utun0 prefixlen 64 scopeid 0x18 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet 10.7.7.1 --> 10.7.7.2 netmask 0xffffffff 
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::f3ba:b6f2:23ba:c4a7%utun2 prefixlen 64 scopeid 0x1b 
	nd6 options=201<PERFORMNUD,DAD>
utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::bf2f:142:5c7:cc19%utun3 prefixlen 64 scopeid 0x1d 
	nd6 options=201<PERFORMNUD,DAD>
utun4: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::7c53:6c94:c367:b070%utun4 prefixlen 64 scopeid 0x1e 
	nd6 options=201<PERFORMNUD,DAD>
utun5: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::5f8b:e2e9:d834:6112%utun5 prefixlen 64 scopeid 0x1f 
	nd6 options=201<PERFORMNUD,DAD>
utun6: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::c161:5f52:d887:17e%utun6 prefixlen 64 scopeid 0x20 
	nd6 options=201<PERFORMNUD,DAD>
utun7: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::391f:3260:cd99:d0df%utun7 prefixlen 64 scopeid 0x23 
	nd6 options=201<PERFORMNUD,DAD>
```

**Comment by jkbullard** [comment]
Maybe the multiple utuns have nothing at all to do with Tunnelblick or OpenVPN!!!

I had a vague memory of reading that an Apple service was creating utun devices. (Back to my Mac or screen sharing, or maybe something else.)

I created a fresh install of Catalina 10.15.2 in a VM. Here's what I get:
<pre>
ifconfig -a
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::7cd3:6e53:724b:dbe0%utun0 prefixlen 64 scopeid 0x5 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::534f:f1f4:c531:a173%utun1 prefixlen 64 scopeid 0x6 
	nd6 options=201<PERFORMNUD,DAD>
</pre>

So, even on a minimally installed Catalina (no location services, Siri, Apple ID, etc.), macOS itself creates two utuns.

Maybe you have additional Apple (or other) services enabled that use utun2 through utun7?

Also, your utuns have various MTUs. I would expect all utuns created by an instance of OpenVPN to have the same MTU.

@essandess - Whether or not Tunnelblick/OpenVPN are creating these multiple utuns, going back to your original post, the problem wasn't that multiple utuns were created, it was that you (or your scripts) didn't have a way of knowing what utun was being used by the VPN. OpenVPN makes the device available to the "up" script, so that script could save it somewhere that would be accessible to Tunnelblick itself and then Tunnelblick could include it in the arguments with which it starts Tunnelblick VPN Configuration scripts such as "post-disconnect.sh". Would that help you?

**Comment by essandess** [comment]
It's strange, and I haven't been able to track down the cause.

> OpenVPN makes the device available to the "up" script, so that script could save it somewhere that would be accessible to Tunnelblick itself and then Tunnelblick could include it in the arguments with which it starts Tunnelblick VPN Configuration scripts such as "post-disconnect.sh". Would that help you?

Yes, if there was some way to run an auxiliary script after the "up" script runs. `pf` rules are loaded at boot time, so the rules would have to be flushed and reloaded after the "up" script saves whichever interface it uses. See, e.g. https://github.com/macports/macports-ports/blob/master/net/macos-fortress/files/pf.conf . It will be necessary to run:

> `pfctl -Fall && pfctl -ef /path/to/pf_vpn.conf`

**Comment by jkbullard** [comment]
>> OpenVPN makes the device available to the "up" script, so that script could save it somewhere that would be accessible to Tunnelblick itself and then Tunnelblick could include it in the arguments with which it starts Tunnelblick VPN Configuration scripts such as "post-disconnect.sh". Would that help you?

> Yes, if there was some way to run an auxiliary script after the "up" script runs.

@essandess - **There is a way to do exactly that.**

It's not documented (yet, but I'll try to document it in [Using Scripts](https://tunnelblick.net/cUsingScripts.html) soon), but you can include an "up-suffix.sh" script in the same folder as the config.ovpn file (inside ___.tblk/Contents/Resources). It will be run at the end of the "up" script and will be called with the same arguments as the "up" script is called, which are:

* for tun: `tun_dev  tun_mtu  link_mtu  ifconfig_local_ip  ifconfig_remote_ip [ init | restart ]`

* for tap: `tap_dev  tap_mtu  link_mtu  ifconfig_local_ip  ifconfig_netmask [ init | restart ]`

(So the first argument will be "utun8" or similar.)

There can be similar "up-prefix.sh", "down-prefix.sh", and "down-suffix.sh" scripts, too.

Please file an Issue if there are any problems with this feature: because it isn't documented, it's likely that nobody has ever used it.

**Comment by jkbullard** [comment]
There can also be "route-pre-down-prefix.sh" and "route-pre-down-suffix.sh" scripts.

**Comment by jkbullard** [comment]
I have documented the prefix and suffix scripts at [Using Scripts](https://tunnelblick.net/cUsingScripts.html).

One correction to my [earlier comment](https://github.com/Tunnelblick/Tunnelblick/issues/340#issuecomment-568226497): the scripts are called with a varying number of Tunnelblick arguments first, before the OpenVPN arguments. For details see [Using Scripts](https://tunnelblick.net/cUsingScripts.html).

**Comment by byaussy** [comment]
I realize this is an old thread, but seems to be related to a problem we're having recently (the past several days) with our Tunnelblick(3.8.4a (build 5601) mac users.

Before connecting Tunnelblick, `ifconfig -a` is showing these utun interfaces:
```
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::eb63:a4e1:97ed:c74e%utun0 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::c26a:3de2:95b7:275f%utun1 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
```

Clicking connect results in the following diagnostic log snippet:
```
2020-12-16 09:36:35.684478 Opening utun (connect(AF_SYS_CONTROL)): Resource busy (errno=16)
2020-12-16 09:36:35.684495 Opening utun (connect(AF_SYS_CONTROL)): Resource busy (errno=16)
2020-12-16 09:36:35.684619 Opened utun device utun2
2020-12-16 09:36:35.684661 MANAGEMENT: >STATE:1608129395,ADD_ROUTES,,,,,,
2020-12-16 09:36:35.684674 /sbin/route add -net 192.168.16.0 10.8.0.1 255.255.255.0
                           add net 192.168.16.0: gateway 10.8.0.1
```

At this point, routes through the tunnel are failing with `network is unreachable`, and `ifconfig -a` is still showing the (stale?) utun2 interface with no inet entry:
```
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::eb63:a4e1:97ed:c74e%utun0 prefixlen 64 scopeid 0x10 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::c26a:3de2:95b7:275f%utun1 prefixlen 64 scopeid 0x11 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
```

After several disconnect/connect cycles, I finally get a slightly different diagnostic log output. Snippet is here:
```
2020-12-16 10:04:42.818975 Opening utun (connect(AF_SYS_CONTROL)): Resource busy (errno=16)
2020-12-16 10:04:42.819008 Opening utun (connect(AF_SYS_CONTROL)): Resource busy (errno=16)
2020-12-16 10:04:42.819196 Opened utun device utun2
2020-12-16 10:04:42.819232 MANAGEMENT: >STATE:1608131082,ASSIGN_IP,,10.8.0.238,,,,
2020-12-16 10:04:42.819268 /sbin/ifconfig utun2 delete
                           ifconfig: ioctl (SIOCDIFADDR): Can't assign requested address
2020-12-16 10:04:42.829642 NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
2020-12-16 10:04:42.829682 /sbin/ifconfig utun2 10.8.0.238 10.8.0.238 netmask 255.255.255.0 mtu 1500 up
2020-12-16 10:04:42.831682 /sbin/route add -net 10.8.0.0 10.8.0.238 255.255.255.0
                           add net 10.8.0.0: gateway 10.8.0.238
2020-12-16 10:04:42.834166 MANAGEMENT: >STATE:1608131082,ADD_ROUTES,,,,,,
2020-12-16 10:04:42.834191 /sbin/route add -net 192.168.16.0 10.8.0.1 255.255.255.0
                           add net 192.168.16.0: gateway 10.8.0.1
```

As you can see, this time Tunnelblick actually attempted deletion of the pre-existing tun/tap instance, and then recreated utun2.

This worked, but what I don't understand is why it took several disconnect/connect cycles before Tunnelblick tried to delete utun2. Is there some configuration we can change to make sure this happens on every connect attempt?

**Comment by jkbullard** [comment]
As far as I know, there isn't any setting you can change that would affect this, but different versions of OpenVPN might.

Am I correct in understanding that
 * Your setups use OpenVPN 2.4.9; and
 * The problem did not occur when you were using Tunnelblick 3.8.4, and only shows up when using Tunnelblick 3.8.4a?

Have you tried Tunnelblick 3.8.5beta02, which includes OpenVPN 2.4.10?

The reason I'm asking about OpenVPN is that Tunnelblick itself does nothing with utun devices. Such low-level manipulation is done by OpenVPN. (The log messages you posted are coming from OpenVPN; Tunnelblick is just displaying them.) Tunnelblick 3.8.4 and 3.8.4a both use the same OpenVPN 2.4.9 source code, and there are no other changes that would affect utun. The only difference is that OpenVPN is static linked to a newer version of OpenSSL in 3.8.4a.

The utun devices are used by macOS itself and by Apple applications, so it isn't surprising that they are created and destroyed independently of Tunnelblick/OpenVPN.
