### ISSUE TITLE
Warning: Unknown OpenVPN processes

### ISSUE THREAD

**Issue by ryandesign** [Tunnelblick/Tunnelblick#853]
I have an M1 Mac mini with three volumes, each having a different macOS version (13, 14, 15). Each is configured to auto-login to macOS and each has Tunnelblick 8.0 installed and configured to connect to my VPN on login. I frequently reboot between the different OS versions.

Frequently, immediately after startup/login/connection, I get a dialog that says:

> Warning: Unknown OpenVPN processes
>
> One or more OpenVPN processes are running but are unknown to Tunnelblick. If you are not running OpenVPN separately from Tunnelblick, this usually means that an earlier launch of Tunnelblick was unable to shut them down properly and you should terminate them. They are likely to interfere with Tunnelblick's operation. Do you wish to terminate them?
>
> [ ] Do not ask again, always 'Ignore'
>
> [Terminate] [Ignore]

![Screenshot](https://github.com/user-attachments/assets/249f6157-e84b-4c88-8d0d-271dbad4fa6b)

**Comment by jkbullard** [comment]
Thanks for your report. I haven't been able to reproduce it, but have found a potential race condition that might cause it. It will be fixed in the next beta release later this month.

Let's leave this Issue open until then.

**Comment by jkbullard** [comment]
@ryandesign - Tunnelblick 8.1betea01 has been released and should fix this problem.

**Comment by ryandesign** [comment]
The problem still occurs with 8.1beta03.

**Comment by jkbullard** [comment]
@ryandesign - Please post the output from copy/pasting the following into /Applications/Utilities/Terminal:

defaults read net.tunnelblick.tunnelblick

**Comment by ryandesign** [comment]
Since I have three OS volumes I'll give you that info from each of them:

<details>
<summary>macOS 13.7.1</summary>

```
% sw_vers
ProductName:		macOS
ProductVersion:		13.7.1
BuildVersion:		22H221
% defaults read net.tunnelblick.tunnelblick
{
    "*-notOKToCheckThatIPAddressDidNotChangeAfterConnection" = 1;
    AdvancedWindowTabIdentifier = connectingAndDisconnecting;
    "NERV-keepConnected" = 1;
    "NERV-keychainHasUsernameAndPassword" = 1;
    "NERV-lastConnectionSucceeded" = 1;
    "NERV-loginWindowSecurityTokenCheckboxIsChecked" = 0;
    "NERV-onSystemStart" = 0;
    NERVautoConnect = 1;
    "NSWindow Frame ConnectingWindow" = "765 649 389 217 0 0 1920 1055 ";
    "NSWindow Frame SUStatusFrame" = "760 711 400 135 0 0 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "650 514 620 398 0 0 1920 1055 ";
    "NSWindow Frame SettingsSheetWindow" = "556 196 829 548 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2025-08-03 00:37:20 +0000";
    SUScheduledCheckInterval = 86400;
    connectionWindowDisplayCriteria = showWhenConnectingAndConnected;
    detailsWindowConfigurationsTabIdentifier = log;
    detailsWindowFrame = "{{500, 421}, {920, 522}}";
    detailsWindowFrameVersion = 6340;
    detailsWindowLeftFrame = "{{0, 0}, {167, 402}}";
    detailsWindowViewIndex = 2;
    haveDealtWithAfterDisconnect = 1;
    haveDealtWithAlwaysShowLoginWindow = 1;
    haveDealtWithOldLoginItem = 1;
    haveDealtWithOldTunTapPreferences = 1;
    keyboardShortcutIndex = 1;
    lastConnectedDisplayName = NERV;
    lastLanguageAtLaunchWasRTL = 0;
    lastLaunchTime = "775874239.654415";
    launchAtNextLogin = 1;
    leftNavSelectedDisplayName = NERV;
    maxLogDisplaySize = 102400;
    skipWarningAboutDnsProblems = 1;
    tunnelblickVersionHistory =     (
        "8.1beta03 (build 6340)",
        "8.0 (build 6300)",
        "6.0.1 (build 6161)",
        "4.0.1 (build 5971)",
        "4.0.0 (build 5970)",
        "3.8.8g (build 5779.3)",
        "3.8.8f (build 5779.2)",
        "3.8.8e (build 5779.1)",
        "3.8.8d (build 5779)",
        "3.8.8c (build 5778)"
    );
    updateCheckAutomatically = 1;
    updateCheckBetas = 1;
}
```
</details>

<details>
<summary>macOS 14.7.1</summary>

```
% sw_vers
ProductName:		macOS
ProductVersion:		14.7.1
BuildVersion:		23H222
% defaults read net.tunnelblick.tunnelblick
{
    "*-notOKToCheckThatIPAddressDidNotChangeAfterConnection" = 1;
    AdvancedWindowTabIdentifier = connectingAndDisconnecting;
    "NERV-keepConnected" = 1;
    "NERV-keychainHasUsernameAndPassword" = 1;
    "NERV-lastConnectionSucceeded" = 1;
    "NERV-loginWindowSecurityTokenCheckboxIsChecked" = 0;
    "NERV-onSystemStart" = 0;
    NERVautoConnect = 1;
    "NSWindow Frame ConnectingWindow" = "765 649 389 217 0 0 1920 1055 ";
    "NSWindow Frame SUStatusFrame" = "760 711 400 135 0 0 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "650 514 620 398 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2025-08-03 00:39:30 +0000";
    SUScheduledCheckInterval = 86400;
    connectionWindowDisplayCriteria = showWhenConnectingAndConnected;
    detailsWindowConfigurationsTabIdentifier = log;
    detailsWindowFrame = "{{500, 421}, {920, 522}}";
    detailsWindowFrameVersion = 6340;
    detailsWindowLeftFrame = "{{0, 0}, {167, 402}}";
    detailsWindowViewIndex = 4;
    haveDealtWithAfterDisconnect = 1;
    haveDealtWithAlwaysShowLoginWindow = 1;
    haveDealtWithOldLoginItem = 1;
    haveDealtWithOldTunTapPreferences = 1;
    keyboardShortcutIndex = 1;
    lastConnectedDisplayName = NERV;
    lastLanguageAtLaunchWasRTL = 0;
    lastLaunchTime = "775874368.1862659";
    launchAtNextLogin = 1;
    leftNavSelectedDisplayName = NERV;
    maxLogDisplaySize = 102400;
    skipWarningAboutDnsProblems = 1;
    tunnelblickVersionHistory =     (
        "8.1beta03 (build 6340)",
        "8.0 (build 6300)",
        "6.0.1 (build 6161)",
        "6.0 (build 6160)",
        "4.0.1 (build 5971)",
        "4.0.0 (build 5970)",
        "3.8.8g (build 5779.3)",
        "3.8.8f (build 5779.2)",
        "3.8.8e (build 5779.1)",
        "3.8.8d (build 5779)"
    );
    updateCheckAutomatically = 1;
    updateCheckBetas = 1;
}
```
</details>

<details>
<summary>macOS 15.3.1</summary>

```
% sw_vers
ProductName:		macOS
ProductVersion:		15.3.1
BuildVersion:		24D70
% defaults read net.tunnelblick.tunnelblick
{
    "*-notOKToCheckThatIPAddressDidNotChangeAfterConnection" = 1;
    AdvancedWindowTabIdentifier = connectingAndDisconnecting;
    "NERV-allowChangesToManuallySetNetworkSettings" = 1;
    "NERV-keepConnected" = 1;
    "NERV-keychainHasUsernameAndPassword" = 1;
    "NERV-lastConnectionSucceeded" = 1;
    "NERV-loginWindowSecurityTokenCheckboxIsChecked" = 0;
    "NERV-onSystemStart" = 0;
    NERVautoConnect = 1;
    "NSWindow Frame ConnectingWindow" = "765 649 389 217 0 0 1920 1055 ";
    "NSWindow Frame SUStatusFrame" = "760 708 400 135 0 0 1920 1055 ";
    "NSWindow Frame SUUpdateAlert" = "939 560 620 398 0 0 1920 1055 ";
    "NSWindow Frame SettingsSheetWindow" = "258 410 829 548 0 0 1920 1055 ";
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2025-08-02 13:45:07 +0000";
    SUScheduledCheckInterval = 86400;
    connectionWindowDisplayCriteria = showWhenConnectingAndConnected;
    detailsWindowConfigurationsTabIdentifier = log;
    detailsWindowFrame = "{{500, 421}, {920, 522}}";
    detailsWindowFrameVersion = 6340;
    detailsWindowLeftFrame = "{{0, 0}, {167, 402}}";
    detailsWindowViewIndex = 2;
    haveDealtWithAfterDisconnect = 1;
    haveDealtWithAlwaysShowLoginWindow = 1;
    haveDealtWithOldLoginItem = 1;
    haveDealtWithOldTunTapPreferences = 1;
    keyboardShortcutIndex = 1;
    lastConnectedDisplayName = NERV;
    lastLanguageAtLaunchWasRTL = 0;
    lastLaunchTime = "775835107.626382";
    launchAtNextLogin = 1;
    leftNavSelectedDisplayName = NERV;
    maxLogDisplaySize = 102400;
    skipWarningAboutDnsProblems = 1;
    tunnelblickVersionHistory =     (
        "8.1beta03 (build 6340)",
        "8.0 (build 6300)",
        "6.0.1 (build 6161)",
        "6.0 (build 6160)",
        "4.0.1 (build 5971)",
        "4.0.0 (build 5970)",
        "3.8.8g (build 5779.3)",
        "3.8.8f (build 5779.2)",
        "3.8.8e (build 5779.1)",
        "3.8.8d (build 5779)"
    );
    updateCheckAutomatically = 1;
    updateCheckBetas = 1;
}
```
</details>

This server is going away soon but I'll let you know if I still see the problem on its replacement, which will have fresh OS and Tunnelblick installations.

**Comment by ryandesign** [comment]
The new setup uses VMs running in UTM, and yes, I do still see this problem there occasionally.
